# Define the name of the workflow, which runs unit tests.
name: Unit Tests

# Define when this workflow should be triggered.
on:
  # Trigger the workflow on pull requests targeting the "main" branch.
  pull_request:
    branches: [ "main" ]

  # Allow manual triggering of the workflow from the GitHub Actions UI.
  workflow_dispatch:

# Define the jobs to be executed within this workflow.
jobs:
  # Define a job named "unit-tests".
  unit-tests:
    # Specify the type of machine (runner) this job will run on.
    runs-on: ubuntu-latest

    # Define the steps to be executed as part of this job.
    steps:
      # Step 1: Checkout the repository's code.
      - name: Checkout code
        uses: actions/checkout@main

      # Step 2: Run unit tests.
      - name: Run unit tests
        # Execute Python's unittest module to discover and run tests.
        # -m unittest runs the unittest module as a script.
        # discover: Discover and run all tests in the specified directory.
        # -s ./unit_tests/: Specifies the directory where tests are located.
        # -p 'utest_*.py': Looks for files starting with 'utest_' and ending with '.py'.
        run: python -m unittest discover -s ./unit_tests/ -p 'utest_*.py'
